### ISSUE TITLE
Details including screenshots.

### ISSUE THREAD

**Issue by ghost** [megasaturnv/arduino-gps-tracker#2]
Hey there,
I am new to Arduino and still learning the basics. I wanted to build a similar project to yours. Is there a way you to include some pictures in your readme? I'd be grateful!

**Comment by megasaturnv** [comment]
I'll see what I can do, might be a few days though! :)

I admit this project isn't the most intuitive, so photos will definitely help. I should do a bit more work on this project as the documentation is incomplete.

**Comment by megasaturnv** [comment]
Closing off this issue. Images of the device can be found in the [README.md](../tree/master/README.md) and [/docs](../tree/master/docs) Feel free to re-open if you need further assistance. Screenshots for how to produce maps can be found  in [/maps](../tree/master/maps). The documentation is still being written for this.
